# Generated by Django 4.1.4 on 2022-12-15 02:37

from django.db import migrations, models
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_designation',
            field=models.CharField(blank=True, default='Blogger', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to='authorimages/'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Tech', 'Tech'), ('Jobs', 'Jobs'), ('business', 'business'), ('sports', 'sports')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=300, unique=True),
        ),
    ]
