# Generated by Django 4.1.3 on 2022-12-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_author_designation_post_author_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_designation',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
