# Generated by Django 4.1.3 on 2022-12-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_post_author_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_img',
        ),
    ]
