# Generated by Django 4.1.4 on 2022-12-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Travel', 'Travel'), ('Food', 'Food'), ('Tech', 'Tech'), ('Jobs', 'Jobs'), ('business', 'business'), ('sports', 'sports')], default='Uncategorized', max_length=50),
        ),
    ]
